import type { EventCategory } from "./constants";
import { SOURCE_URL } from "./constants";

type SeedEvent = {
  title: string;
  category: EventCategory;
  dept: string;
  startDate: string; // YYYY-MM-DD
  endDate: string;
  location?: string;
  contact?: string;
  description?: string;
};

const CONTACT = "02-3399-3153";
const DEPT = "교무처";
/** 공휴일·국경일 — 구분은 category=HOLIDAY(표시: 공휴일), 담당부서는 비움 */
const HOLIDAY_DEPT = "";
const DESC = `출처: ${SOURCE_URL}`;

/** 공식 학사주요일정 2026.09 ~ 2027.02 */
export const OFFICIAL_ACADEMIC_EVENTS: SeedEvent[] = [
  { title: "개강", category: "ACADEMIC", dept: DEPT, startDate: "2026-09-01", endDate: "2026-09-01", contact: CONTACT, description: DESC },
  { title: "수강신청 확인 및 정정 기간(1주차)", category: "ACADEMIC", dept: DEPT, startDate: "2026-09-01", endDate: "2026-09-07", contact: CONTACT, description: DESC },
  { title: "수강 중도포기(4주차)", category: "ACADEMIC", dept: DEPT, startDate: "2026-09-21", endDate: "2026-09-23", contact: CONTACT, description: DESC },
  { title: "추석", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2026-09-24", endDate: "2026-09-27", description: DESC },
  { title: "개천절", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2026-10-03", endDate: "2026-10-03", description: DESC },
  { title: "대체휴일", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2026-10-05", endDate: "2026-10-05", description: DESC },
  { title: "천보축전", category: "STUDENT", dept: "학생복지처", startDate: "2026-10-06", endDate: "2026-10-06", description: DESC },
  { title: "체육대회", category: "STUDENT", dept: "학생복지처", startDate: "2026-10-07", endDate: "2026-10-07", description: DESC },
  { title: "한글날", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2026-10-09", endDate: "2026-10-09", description: DESC },
  { title: "개교기념일", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2026-10-10", endDate: "2026-10-10", description: DESC },
  { title: "중간강의평가(7주차)", category: "ACADEMIC", dept: DEPT, startDate: "2026-10-13", endDate: "2026-10-30", contact: CONTACT, description: DESC },
  { title: "중간고사(8주차)", category: "ACADEMIC", dept: DEPT, startDate: "2026-10-20", endDate: "2026-10-26", contact: CONTACT, description: DESC },
  { title: "온라인수업 권장주간", category: "ACADEMIC", dept: DEPT, startDate: "2026-10-27", endDate: "2026-11-02", contact: CONTACT, description: DESC },
  { title: "중간고사 성적입력기간", category: "ACADEMIC", dept: DEPT, startDate: "2026-10-27", endDate: "2026-11-02", contact: CONTACT, description: DESC },
  { title: "사랑나눔축제", category: "CHAPEL", dept: "교목처", startDate: "2026-11-09", endDate: "2026-11-12", description: DESC },
  { title: "대학수학능력시험", category: "ADMISSION", dept: "입학처", startDate: "2026-11-19", endDate: "2026-11-19", description: DESC },
  { title: "논술고사", category: "ADMISSION", dept: "입학처", startDate: "2026-11-23", endDate: "2026-11-24", description: DESC },
  { title: "계절학기 수강신청", category: "ACADEMIC", dept: DEPT, startDate: "2026-11-23", endDate: "2026-11-25", contact: CONTACT, description: DESC },
  { title: "기말고사(15주차)", category: "ACADEMIC", dept: DEPT, startDate: "2026-12-08", endDate: "2026-12-14", contact: CONTACT, description: DESC },
  { title: "성적입력기간", category: "ACADEMIC", dept: DEPT, startDate: "2026-12-08", endDate: "2026-12-21", contact: CONTACT, description: DESC },
  { title: "교수협의회", category: "DEPT", dept: DEPT, startDate: "2026-12-15", endDate: "2026-12-15", contact: CONTACT, description: DESC },
  { title: "동계계절학기", category: "ACADEMIC", dept: DEPT, startDate: "2026-12-21", endDate: "2027-01-12", contact: CONTACT, description: DESC },
  { title: "성적확인 및 정정기간", category: "ACADEMIC", dept: DEPT, startDate: "2026-12-22", endDate: "2026-12-28", contact: CONTACT, description: DESC },
  { title: "성탄절", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2026-12-25", endDate: "2026-12-25", description: DESC },
  { title: "종무식", category: "DEPT", dept: DEPT, startDate: "2026-12-31", endDate: "2026-12-31", contact: CONTACT, description: DESC },
  { title: "신정", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2027-01-01", endDate: "2027-01-01", description: DESC },
  { title: "신년 교례회 및 시무식", category: "DEPT", dept: DEPT, startDate: "2027-01-04", endDate: "2027-01-04", contact: CONTACT, description: DESC },
  { title: "교역자계절대학", category: "DEPT", dept: "교목처", startDate: "2027-01-04", endDate: "2027-01-15", description: DESC },
  { title: "계절학기 성적입력기간", category: "ACADEMIC", dept: DEPT, startDate: "2027-01-07", endDate: "2027-01-12", contact: CONTACT, description: DESC },
  { title: "계절학기 성적확인 및 정정기간", category: "ACADEMIC", dept: DEPT, startDate: "2027-01-13", endDate: "2027-01-13", contact: CONTACT, description: DESC },
  { title: "졸업사정회", category: "ACADEMIC", dept: DEPT, startDate: "2027-01-25", endDate: "2027-01-25", contact: CONTACT, description: DESC },
  { title: "예비수강신청", category: "ACADEMIC", dept: DEPT, startDate: "2027-02-01", endDate: "2027-02-03", contact: CONTACT, description: DESC },
  { title: "설날", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2027-02-06", endDate: "2027-02-08", description: DESC },
  { title: "대체휴일", category: "HOLIDAY", dept: HOLIDAY_DEPT, startDate: "2027-02-09", endDate: "2027-02-09", description: DESC },
  { title: "전기 학위수여식", category: "ACADEMIC", dept: DEPT, startDate: "2027-02-12", endDate: "2027-02-12", location: "대강당", contact: CONTACT, description: DESC },
  { title: "본수강신청", category: "ACADEMIC", dept: DEPT, startDate: "2027-02-15", endDate: "2027-02-17", contact: CONTACT, description: DESC },
  { title: "재학생 등록기간", category: "ACADEMIC", dept: DEPT, startDate: "2027-02-17", endDate: "2027-02-23", contact: CONTACT, description: DESC },
  { title: "MVP CAMP(1차)", category: "DEPT", dept: DEPT, startDate: "2027-02-17", endDate: "2027-02-19", contact: CONTACT, description: DESC },
  { title: "교직원 영성축제", category: "CHAPEL", dept: "교목처", startDate: "2027-02-22", endDate: "2027-02-25", description: DESC },
  { title: "교수협의회", category: "DEPT", dept: DEPT, startDate: "2027-02-22", endDate: "2027-02-23", contact: CONTACT, description: DESC },
  { title: "MVP CAMP(2차)", category: "DEPT", dept: DEPT, startDate: "2027-02-22", endDate: "2027-02-24", contact: CONTACT, description: DESC },
  { title: "편입생 오리엔테이션", category: "ADMISSION", dept: "입학처", startDate: "2027-02-24", endDate: "2027-02-24", description: DESC },
  { title: "BFFL 세미나", category: "DEPT", dept: DEPT, startDate: "2027-02-24", endDate: "2027-02-25", contact: CONTACT, description: DESC },
  { title: "신입생·편입생 수강신청", category: "ACADEMIC", dept: DEPT, startDate: "2027-02-25", endDate: "2027-02-26", contact: CONTACT, description: DESC },
  { title: "휴·복학 만기일", category: "ACADEMIC", dept: DEPT, startDate: "2027-02-26", endDate: "2027-02-26", contact: CONTACT, description: DESC },
];

/** 로컬 일정 테스트용 (맵 스냅샷과 별도, 사번 우회 로그인도 가능) */
export const SEED_USERS = [
  {
    employeeId: "admin001",
    name: "김관리",
    department: "기획처",
    role: "ADMIN",
    isTeamLeader: true,
    phoneParent: "기획처",
    phoneDept: "기획처",
    phoneExt: "3390",
  },
  {
    employeeId: "academic001",
    name: "이교무",
    department: "교무처",
    role: "USER",
    isTeamLeader: true,
    phoneParent: "교무처",
    phoneDept: "교무처",
    phoneExt: "3101",
  },
  {
    employeeId: "academic002",
    name: "김학사",
    department: "교무처",
    role: "USER",
    isTeamLeader: false,
    phoneParent: "교무처",
    phoneDept: "학사지원팀",
    phoneExt: "3102",
  },
  {
    employeeId: "chapel001",
    name: "박교목",
    department: "교목처",
    role: "USER",
    isTeamLeader: true,
    phoneParent: "교목처",
    phoneDept: "교목처",
    phoneExt: "3330",
  },
  {
    employeeId: "chapel002",
    name: "한영성",
    department: "교목처",
    role: "USER",
    isTeamLeader: false,
    phoneParent: "교목처",
    phoneDept: "리더십센터",
    phoneExt: "3331",
  },
  {
    employeeId: "student001",
    name: "최학생",
    department: "학생복지처",
    role: "USER",
    isTeamLeader: true,
    phoneParent: "학생처",
    phoneDept: "학생복지팀",
    phoneExt: "3220",
  },
  {
    employeeId: "student002",
    name: "윤축제",
    department: "학생복지처",
    role: "USER",
    isTeamLeader: false,
    phoneParent: "학생처",
    phoneDept: "학생복지팀",
    phoneExt: "3223",
  },
  {
    employeeId: "admission001",
    name: "정입학",
    department: "입학처",
    role: "USER",
    isTeamLeader: true,
    phoneParent: "입학처",
    phoneDept: "입학팀",
    phoneExt: "3360",
  },
  {
    employeeId: "admission002",
    name: "오입시",
    department: "입학처",
    role: "USER",
    isTeamLeader: false,
    phoneParent: "입학처",
    phoneDept: "입학팀",
    phoneExt: "3361",
  },
];

/** 부서 담당자 더미 일정 (초안 + 일부 전체일정 제출분) */
export const DUMMY_DEPT_EVENTS: (SeedEvent & {
  status: "DRAFT" | "PUBLISHED";
  createdById: string;
  createdByName: string;
})[] = [
  // 교무처 — 초안 (담당자 2명)
  {
    title: "캡스톤디자인 중간점검 설명회",
    category: "ACADEMIC",
    dept: "교무처",
    startDate: "2026-10-14",
    endDate: "2026-10-14",
    location: "요한관 201호",
    contact: "이교무 (내선 3114)",
    description: "더미: 학과 캡스톤 중간점검 안내",
    status: "DRAFT",
    createdById: "academic001",
    createdByName: "이교무",
  },
  {
    title: "교양교과 개편 워크숍",
    category: "ACADEMIC",
    dept: "교무처",
    startDate: "2026-11-05",
    endDate: "2026-11-05",
    location: "교수학습개발센터",
    contact: "김학사 (내선 3120)",
    description: "더미: 2027 교양과정 개편 논의",
    status: "DRAFT",
    createdById: "academic002",
    createdByName: "김학사",
  },
  {
    title: "성적 입력 시스템 점검",
    category: "DEPT",
    dept: "교무처",
    startDate: "2026-12-01",
    endDate: "2026-12-02",
    location: "전산원 / SU-Wings",
    contact: "김학사",
    description: "더미: 기말 성적입력 전 시스템 점검",
    status: "DRAFT",
    createdById: "academic002",
    createdByName: "김학사",
  },
  // 교무처 — 이미 전체일정 제출
  {
    title: "학과장 협의회",
    category: "DEPT",
    dept: "교무처",
    startDate: "2026-09-18",
    endDate: "2026-09-18",
    location: "본관 회의실",
    contact: "이교무 (내선 3114)",
    description: "더미: 제출 완료된 부서 일정",
    status: "PUBLISHED",
    createdById: "academic001",
    createdByName: "이교무",
  },

  // 교목처
  {
    title: "채플 좌석 배정 안내",
    category: "CHAPEL",
    dept: "교목처",
    startDate: "2026-09-08",
    endDate: "2026-09-10",
    location: "대강당",
    contact: "박교목 (내선 3200)",
    description: "더미: 학년별 채플 좌석 확정",
    status: "DRAFT",
    createdById: "chapel001",
    createdByName: "박교목",
  },
  {
    title: "기도회 인도자 오리엔테이션",
    category: "CHAPEL",
    dept: "교목처",
    startDate: "2026-10-28",
    endDate: "2026-10-28",
    location: "교목처 세미나실",
    contact: "한영성",
    description: "더미: 사랑나눔축제 준비 기도회",
    status: "DRAFT",
    createdById: "chapel002",
    createdByName: "한영성",
  },
  {
    title: "교직원 기도회",
    category: "CHAPEL",
    dept: "교목처",
    startDate: "2026-09-30",
    endDate: "2026-09-30",
    location: "대강당",
    contact: "박교목",
    description: "더미: 제출된 교목 행사",
    status: "PUBLISHED",
    createdById: "chapel001",
    createdByName: "박교목",
  },

  // 학생복지처
  {
    title: "동아리 박람회 부스 신청 마감",
    category: "STUDENT",
    dept: "학생복지처",
    startDate: "2026-09-10",
    endDate: "2026-09-10",
    location: "학생회관",
    contact: "최학생 (내선 3300)",
    description: "더미: 동아리 박람회 사전 신청",
    status: "DRAFT",
    createdById: "student001",
    createdByName: "최학생",
  },
  {
    title: "체육대회 응원단 리허설",
    category: "STUDENT",
    dept: "학생복지처",
    startDate: "2026-10-05",
    endDate: "2026-10-06",
    location: "대운동장",
    contact: "윤축제",
    description: "더미: 한마음 체육대회 준비",
    status: "DRAFT",
    createdById: "student002",
    createdByName: "윤축제",
  },
  {
    title: "학생 복지 간담회",
    category: "STUDENT",
    dept: "학생복지처",
    startDate: "2026-11-20",
    endDate: "2026-11-20",
    location: "학생회관 회의실",
    contact: "최학생",
    description: "더미: 제출된 학생 행사",
    status: "PUBLISHED",
    createdById: "student001",
    createdByName: "최학생",
  },

  // 입학처
  {
    title: "수시 면접고사 감독 사전교육",
    category: "ADMISSION",
    dept: "입학처",
    startDate: "2026-10-15",
    endDate: "2026-10-15",
    location: "입학처 세미나실",
    contact: "정입학 (내선 3380)",
    description: "더미: 면접 감독 교육",
    status: "DRAFT",
    createdById: "admission001",
    createdByName: "정입학",
  },
  {
    title: "고교 방문설명회 (서울권)",
    category: "ADMISSION",
    dept: "입학처",
    startDate: "2026-09-22",
    endDate: "2026-09-26",
    location: "외부(고교)",
    contact: "오입시",
    description: "더미: 수시 홍보 방문",
    status: "DRAFT",
    createdById: "admission002",
    createdByName: "오입시",
  },
  {
    title: "입학상담 콜센터 운영 강화",
    category: "ADMISSION",
    dept: "입학처",
    startDate: "2026-11-17",
    endDate: "2026-11-21",
    location: "입학처",
    contact: "정입학",
    description: "더미: 수능 직후 상담 대응",
    status: "PUBLISHED",
    createdById: "admission001",
    createdByName: "정입학",
  },

  // 기획처 (관리자)
  {
    title: "부서 일정 취합 점검 회의",
    category: "DEPT",
    dept: "기획처",
    startDate: "2026-09-25",
    endDate: "2026-09-25",
    location: "기획처 회의실",
    contact: "김관리",
    description: "더미: 2학기 일정 취합 점검",
    status: "DRAFT",
    createdById: "admin001",
    createdByName: "김관리",
  },
];
