/**
 * 삼육대학교 성과관리종합지수 실제 데이터 (2025년도 기준)
 * 출처: 각 부서 실적 입력 데이터 (2025-09 취합)
 */
import type { CompositeIndex } from "./mockData";

// ── 유틸: 달성률 계산 (null 안전, 상한 150%) ───────────────────────
function ar(actual: number | null, target: number | null): number {
  if (actual == null || target == null || target === 0) return 0;
  return Math.min((actual / target) * 100, 150);
}

// ── 유틸: 가중 점수 합산 → 정규화 점수(0~100) ────────────────────
function ws(pairs: { achieve: number; weight: number }[]): number {
  return pairs.reduce((sum, p) => sum + Math.min(p.achieve, 100) * (p.weight / 100), 0);
}

export const REAL_INDEXES: CompositeIndex[] = [
  // ═══════════════════════════════════════════════════════════
  // 10000 · MVP Edu-Framework 혁신 지수
  // 산출식: A×0.2 + B×0.2 + C×0.2 + D×0.2 + E×0.2
  // ═══════════════════════════════════════════════════════════
  {
    id: "10000",
    name: "MVP Edu-Framework 혁신 지수",
    category: "Ⅰ. 미래교육을 선도하는 MVP 교육혁신",
    description:
      "미래형 학사제도 참여율(A), 융합형 교과목 개발(B), 교원 교수법 역량강화(C), 교원 역량강화 참여시간(D), 적정 전임교원확보율(E)의 5개 지표를 각 20%씩 가중 합산합니다.",
    formula: "A×0.2 + B×0.2 + C×0.2 + D×0.2 + E×0.2",
    // 정규화 점수 = Σ min(달성률,100)×가중치
    score: ws([
      { achieve: ar(27, 27), weight: 20 },        // 10100
      { achieve: ar(0.10, 0.14), weight: 20 },    // 10200
      { achieve: ar(64, 40), weight: 20 },         // 10300
      { achieve: ar(2.32, 2.17), weight: 20 },     // 10400
      { achieve: ar(152.5, 152.5), weight: 20 },   // 10500
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 95, actual: ws([{ achieve: ar(20, 27), weight: 20 }, { achieve: ar(0, 0.14), weight: 20 }, { achieve: ar(36, 40), weight: 20 }, { achieve: ar(2.26, 2.17), weight: 20 }, { achieve: ar(155.84, 152.5), weight: 20 }]) },
      { year: 2023, target: 95, actual: ws([{ achieve: ar(15, 27), weight: 20 }, { achieve: ar(0.05, 0.14), weight: 20 }, { achieve: ar(33, 40), weight: 20 }, { achieve: ar(2.05, 2.17), weight: 20 }, { achieve: ar(149.62, 152.5), weight: 20 }]) },
      { year: 2024, target: 98, actual: ws([{ achieve: ar(27, 27), weight: 20 }, { achieve: ar(0.10, 0.14), weight: 20 }, { achieve: ar(64, 40), weight: 20 }, { achieve: ar(2.32, 2.17), weight: 20 }, { achieve: ar(152.5, 152.5), weight: 20 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "10100",
        name: "미래형 학사제도 참여학생 비율",
        weight: 20,
        formula: "A / B × 100",
        achieveRate: ar(27, 27),
        targetValue: 27,
        actualValue: 27,
        unit: "%",
        trendData: [
          { year: 2022, target: 20, actual: 20 },
          { year: 2023, target: 20, actual: 15 },
          { year: 2024, target: 27, actual: 27 },
          { year: 2025, target: 25, actual: null },
          { year: 2026, target: 30, actual: null },
          { year: 2027, target: 33, actual: null },
        ],
        subIndicators: [
          {
            id: "10101",
            name: "미래형 학사제도 참여학생 수",
            description: "계절학기 선이수제·집중이수제·연계전공·복수전공 등 미래형 학사제도에 참여한 학생 수를 입력하세요.",
            variableKey: "A",
            deptName: "학사지원팀",
            actualValue: 2745,
            targetValue: 2751,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "10102",
            name: "학부 재학생 수",
            description: "학부 전체 재학생 수 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "학사지원팀",
            actualValue: 10027,
            targetValue: 10027,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "ENROLLED_STUDENTS_UG",
          },
        ],
      },
      {
        id: "10200",
        name: "융합형 교과목 개발 건수",
        weight: 20,
        formula: "(A + B) / C × 100",
        achieveRate: ar(0.10, 0.14),
        targetValue: 0.14,
        actualValue: 0.10,
        unit: "%",
        trendData: [
          { year: 2022, target: 0.05, actual: 0 },
          { year: 2023, target: 0.10, actual: 0.05 },
          { year: 2024, target: 0.14, actual: 0.10 },
          { year: 2025, target: 0.30, actual: null },
          { year: 2026, target: 0.60, actual: null },
          { year: 2027, target: 1.00, actual: null },
        ],
        subIndicators: [
          {
            id: "10201",
            name: "융합형 교과목(전공) 개발 건수",
            description: "학년도별 융합형 교과목(전공) 신규 개발 건수를 입력하세요. (2개 이상 학문 분야 융합 교과목)",
            variableKey: "A",
            deptName: "학사지원팀",
            actualValue: 0,
            targetValue: 0,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "10203",
            name: "융합형 교과목(교양) 개발 건수",
            description: "학년도별 융합형 교과목(교양) 신규 개발 건수를 입력하세요. (2개 이상 학문 분야 융합 교양 교과목)",
            variableKey: "B",
            deptName: "교양교육원",
            actualValue: 3,
            targetValue: 3,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "10202",
            name: "개설 교과목 수(전공+교양)",
            description: "학년도 전체 개설 교과목 수(전공+교양 합계) (시스템 자동 연동)",
            variableKey: "C",
            deptName: "학사지원팀",
            actualValue: 2899,
            targetValue: 2102,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "TOTAL_COURSES",
          },
        ],
      },
      {
        id: "10300",
        name: "교원 교수법 역량강화 참여인원",
        weight: 20,
        formula: "A",
        achieveRate: ar(64, 40),
        targetValue: 40,
        actualValue: 64,
        unit: "명",
        trendData: [
          { year: 2022, target: 36, actual: 36 },
          { year: 2023, target: 36, actual: 33 },
          { year: 2024, target: 40, actual: 64 },
          { year: 2025, target: 41, actual: null },
          { year: 2026, target: 42, actual: null },
          { year: 2027, target: 44, actual: null },
        ],
        subIndicators: [
          {
            id: "10301",
            name: "교원 교수법 역량강화 프로그램 참여 교원 수",
            description: "SU-MVP교수법 연수·워크숍 등 교수법 역량강화 프로그램에 참여한 교원 수(연인원)를 입력하세요.",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 64,
            targetValue: 40,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "10400",
        name: "교원 역량강화 프로그램 참여 시간",
        weight: 20,
        formula: "A / B",
        achieveRate: ar(2.32, 2.17),
        targetValue: 2.17,
        actualValue: 2.32,
        unit: "시간/인",
        trendData: [
          { year: 2022, target: 2.17, actual: 2.26 },
          { year: 2023, target: 2.17, actual: 2.05 },
          { year: 2024, target: 2.17, actual: 2.32 },
          { year: 2025, target: 3.88, actual: null },
          { year: 2026, target: 4.11, actual: null },
          { year: 2027, target: 4.33, actual: null },
        ],
        subIndicators: [
          {
            id: "10401",
            name: "교원 역량강화 프로그램 참여 시간(누적)",
            description: "학년도 교원 역량강화 프로그램(교수법 연수, 워크숍 등) 참여 총 시간을 누적 합산하여 입력하세요.",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 485,
            targetValue: 453,
            unit: "시간",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "10402",
            name: "전임교원 수",
            description: "학년도 전임교원 수 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "교수지원팀",
            actualValue: 209,
            targetValue: 209,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "FULL_TIME_FACULTY",
          },
        ],
      },
      {
        id: "10500",
        name: "적정 전임교원확보율",
        weight: 20,
        formula: "A + B",
        achieveRate: ar(152.5, 152.5),
        targetValue: 152.5,
        actualValue: 152.5,
        unit: "지수",
        trendData: [
          { year: 2022, target: 152.5, actual: 155.84 },
          { year: 2023, target: 152.5, actual: 149.62 },
          { year: 2024, target: 152.5, actual: 152.5 },
          { year: 2025, target: 153.41, actual: null },
          { year: 2026, target: 154.18, actual: null },
          { year: 2027, target: 154.96, actual: null },
        ],
        subIndicators: [
          {
            id: "10501",
            name: "과거 5년 평균 대비 전임교원 확보율×0.6",
            description: "최근 5년 평균 전임교원 확보율 대비 당해년도 확보율(%) × 0.6 값을 입력하세요.",
            variableKey: "A",
            deptName: "교수지원팀",
            actualValue: 97.48,
            targetValue: 97.48,
            unit: "%",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "10502",
            name: "정년트랙 전임교원 확보 비율×0.4",
            description: "전임교원 중 정년트랙(테뉴어) 비율(%) × 0.4 값을 입력하세요.",
            variableKey: "B",
            deptName: "교수지원팀",
            actualValue: 55.02,
            targetValue: 55.02,
            unit: "%",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 20000 · MVP 교과교육 혁신 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "20000",
    name: "MVP 교과교육 혁신 지수",
    category: "Ⅱ. 미래를 여는 MVP 교과교육 혁신",
    description:
      "SU핵심역량(A), 디지털·융합 교양교과(B), SU 전공능력(C), 혁신형 전공 교과목 개발·개편(D) 4개 지표를 각 25%씩 합산합니다.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(53.20, 53.30), weight: 25 },   // 20100 2024 실적 53.20
      { achieve: ar(5.34, 6.52), weight: 25 },
      { achieve: ar(2.96, 2.55), weight: 25 },
      { achieve: ar(4, 21), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 85, actual: ws([{ achieve: ar(53.10, 53.30), weight: 25 }, { achieve: ar(4.48, 6.52), weight: 25 }, { achieve: 0, weight: 25 }, { achieve: ar(7, 21), weight: 25 }]) },
      { year: 2023, target: 88, actual: ws([{ achieve: ar(53.20, 53.30), weight: 25 }, { achieve: ar(4.69, 6.52), weight: 25 }, { achieve: ar(2.82, 2.55), weight: 25 }, { achieve: ar(14, 21), weight: 25 }]) },
      { year: 2024, target: 90, actual: ws([{ achieve: ar(53.20, 53.30), weight: 25 }, { achieve: ar(5.34, 6.52), weight: 25 }, { achieve: ar(2.96, 2.55), weight: 25 }, { achieve: ar(4, 21), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "20100",
        name: "SU 핵심역량 지표",
        weight: 25,
        formula: "A",
        achieveRate: ar(53.20, 53.30),
        targetValue: 53.30,
        actualValue: 53.20,
        unit: "%",
        trendData: [
          { year: 2022, target: 53.30, actual: 53.10 },
          { year: 2023, target: 53.30, actual: 53.20 },
          { year: 2024, target: 53.30, actual: 53.20 },
          { year: 2025, target: 53.40, actual: null },
          { year: 2026, target: 53.40, actual: null },
          { year: 2027, target: 53.50, actual: null },
        ],
        subIndicators: [
          {
            id: "20101",
            name: "SU-MVP 핵심역량 목표 달성도",
            description: "SU-핵심역량진단 도구에 의한 핵심역량 점수 목표 달성도(%)를 입력하세요. (IR센터 제공 진단 결과)",
            variableKey: "A",
            deptName: "IR센터",
            actualValue: 53.20,
            targetValue: 53.30,
            unit: "%",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "20200",
        name: "디지털·융합 교양 교과목 개설 비율",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(5.34, 6.52),
        targetValue: 6.52,
        actualValue: 5.34,
        unit: "%",
        trendData: [
          { year: 2022, target: 6.52, actual: 4.48 },
          { year: 2023, target: 6.52, actual: 4.69 },
          { year: 2024, target: 6.52, actual: 5.34 },
          { year: 2025, target: 7.00, actual: null },
          { year: 2026, target: 7.50, actual: null },
          { year: 2027, target: 8.00, actual: null },
        ],
        subIndicators: [
          {
            id: "20201",
            name: "디지털·융합 개설 교과목(교양) 수",
            description: "학년도 내 개설된 디지털·융합 관련 교양 교과목 수를 입력하세요. (SW·AI·데이터 등 디지털 역량 관련 교양 교과목)",
            variableKey: "A",
            deptName: "교양교육원",
            actualValue: 11,
            targetValue: 12,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "20203",
            name: "학년도별 개설 교과목 수(교양)",
            description: "학년도 전체 교양 개설 교과목 수 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "교양교육원",
            actualValue: 206,
            targetValue: 184,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "LIBERAL_ARTS_COURSES",
          },
        ],
      },
      {
        id: "20300",
        name: "SU 전공능력 지표",
        weight: 25,
        formula: "A",
        achieveRate: ar(2.96, 2.55),
        targetValue: 2.55,
        actualValue: 2.96,
        unit: "점",
        trendData: [
          { year: 2022, target: 2.55, actual: null },
          { year: 2023, target: 2.55, actual: 2.82 },
          { year: 2024, target: 2.55, actual: 2.96 },
          { year: 2025, target: 2.58, actual: null },
          { year: 2026, target: 2.58, actual: null },
          { year: 2027, target: 2.58, actual: null },
        ],
        subIndicators: [
          {
            id: "20301",
            name: "SU-MVP 전공능력 목표 달성도",
            description: "전공능력 진단도구에 의한 학과별 전공능력 점수 평균의 목표 달성도(점)를 입력하세요. (학사지원팀 제공 진단 결과)",
            variableKey: "A",
            deptName: "학사지원팀",
            actualValue: 2.96,
            targetValue: 2.55,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "20400",
        name: "혁신형 전공 교과목 개발·개편 비율",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(4, 21),
        targetValue: 21,
        actualValue: 4,
        unit: "%",
        trendData: [
          { year: 2022, target: 21, actual: 7 },
          { year: 2023, target: 21, actual: 14 },
          { year: 2024, target: 21, actual: 4 },
          { year: 2025, target: 23, actual: null },
          { year: 2026, target: 25, actual: null },
          { year: 2027, target: 27, actual: null },
        ],
        subIndicators: [
          {
            id: "20401",
            name: "개발·개편 교과목(전공) 수",
            description: "학년도 내 신규 개발 또는 대폭 개편된 전공 교과목 수를 입력하세요. (강의계획서 기준 30% 이상 변경 포함)",
            variableKey: "A",
            deptName: "학사지원팀",
            actualValue: 104,
            targetValue: 306,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "20402",
            name: "학년도별 개설 교과목 수(전공)",
            description: "학년도 전체 전공 개설 교과목 수 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "학사지원팀",
            actualValue: 2448,
            targetValue: 1440,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "MAJOR_COURSES",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 30000 · 스마트 융합형 교육방법 혁신 지수
  // 산출식: A×0.3 + B×0.3 + C×0.4
  // ═══════════════════════════════════════════════════════════
  {
    id: "30000",
    name: "스마트 융합형 교육방법 혁신 지수",
    category: "Ⅲ. 스마트 융합형 교육방법 혁신",
    description:
      "SU-MVP교수법 적용 교과 비율(A·30%), 에듀테크 기반 강의실 개선(B·30%), 교육콘텐츠 신규 개발(C·40%) 3개 지표를 가중 합산합니다.",
    formula: "A×0.3 + B×0.3 + C×0.4",
    score: ws([
      { achieve: ar(5, 6), weight: 30 },
      { achieve: ar(5, 5), weight: 30 },
      { achieve: ar(90, 550), weight: 40 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 80, actual: ws([{ achieve: ar(5, 6), weight: 30 }, { achieve: ar(2, 5), weight: 30 }, { achieve: ar(450, 550), weight: 40 }]) },
      { year: 2023, target: 85, actual: ws([{ achieve: ar(7, 6), weight: 30 }, { achieve: ar(3, 5), weight: 30 }, { achieve: ar(500, 550), weight: 40 }]) },
      { year: 2024, target: 90, actual: ws([{ achieve: ar(5, 6), weight: 30 }, { achieve: ar(5, 5), weight: 30 }, { achieve: ar(90, 550), weight: 40 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "30100",
        name: "SU-MVP교수법 적용 교과 비율",
        weight: 30,
        formula: "A / B × 100",
        achieveRate: ar(5, 6),
        targetValue: 6,
        actualValue: 5,
        unit: "%",
        trendData: [
          { year: 2022, target: 6, actual: 5 },
          { year: 2023, target: 6, actual: 7 },
          { year: 2024, target: 6, actual: 5 },
          { year: 2025, target: 7.5, actual: null },
          { year: 2026, target: 7.7, actual: null },
          { year: 2027, target: 8.0, actual: null },
        ],
        subIndicators: [
          {
            id: "30101",
            name: "SU-MVP교수법 적용 교과목 수",
            description: "거꾸로교실·팀기반학습(TBL)·문제중심학습(PBL) 등 SU-MVP교수법이 적용된 전공 교과목 수를 입력하세요.",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 123,
            targetValue: 88,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "30102",
            name: "학년도별 개설 교과목 수(전공)",
            description: "학년도 전체 전공 개설 교과목 수 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "학사지원팀",
            actualValue: 2448,
            targetValue: 1440,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "MAJOR_COURSES",
          },
        ],
      },
      {
        id: "30200",
        name: "에듀테크 기반 강의실 개선 건수",
        weight: 30,
        formula: "A",
        achieveRate: ar(5, 5),
        targetValue: 5,
        actualValue: 5,
        unit: "건",
        trendData: [
          { year: 2022, target: 5, actual: 2 },
          { year: 2023, target: 5, actual: 3 },
          { year: 2024, target: 5, actual: 5 },
          { year: 2025, target: 6, actual: null },
          { year: 2026, target: 8, actual: null },
          { year: 2027, target: 9, actual: null },
        ],
        subIndicators: [
          {
            id: "30201",
            name: "에듀테크 기반 강의실 개선 건수",
            description: "스마트 칠판·화상장비·IoT 등 에듀테크 설비를 신규 도입하거나 기존 강의실을 개선한 건수를 입력하세요.",
            variableKey: "A",
            deptName: "시설관리팀",
            actualValue: 5,
            targetValue: 5,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "30300",
        name: "교육콘텐츠 신규 개발 건수",
        weight: 40,
        formula: "A",
        achieveRate: ar(90, 550),
        targetValue: 550,
        actualValue: 90,
        unit: "차시",
        trendData: [
          { year: 2022, target: 550, actual: 450 },
          { year: 2023, target: 550, actual: 500 },
          { year: 2024, target: 550, actual: 90 },
          { year: 2025, target: 600, actual: null },
          { year: 2026, target: 600, actual: null },
          { year: 2027, target: 600, actual: null },
        ],
        subIndicators: [
          {
            id: "30301",
            name: "온라인 교육콘텐츠 신규 개발 건수(차시)",
            description: "학년도 내 신규 개발한 온라인 강의 콘텐츠 총 차시 수를 입력하세요. (동영상 1편 = 1차시 기준)",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 90,
            targetValue: 550,
            unit: "차시",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 40000 · MVP 교육 성과관리 강화 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "40000",
    name: "MVP 교육 성과관리 강화 지수",
    category: "Ⅳ. MVP 교육 성과관리 강화",
    description:
      "인재육성 거버넌스 이행률(A), 교육과정 인증 누적 비율(B), 비교과 프로그램 참여율(C), 인성교육 프로그램 참여 비율(D) 4개 지표 각 25%.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(100, 100), weight: 25 },
      { achieve: ar(26.94, 26.42), weight: 25 },
      { achieve: ar(831.29, 777.82), weight: 25 },
      { achieve: ar(38.59, 27.80), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 95, actual: ws([{ achieve: ar(100, 100), weight: 25 }, { achieve: ar(22.98, 26.42), weight: 25 }, { achieve: ar(842.17, 777.82), weight: 25 }, { achieve: ar(27.18, 27.80), weight: 25 }]) },
      { year: 2023, target: 97, actual: ws([{ achieve: ar(100, 100), weight: 25 }, { achieve: ar(27.68, 26.42), weight: 25 }, { achieve: ar(675.33, 777.82), weight: 25 }, { achieve: ar(26.07, 27.80), weight: 25 }]) },
      { year: 2024, target: 100, actual: ws([{ achieve: ar(100, 100), weight: 25 }, { achieve: ar(26.94, 26.42), weight: 25 }, { achieve: ar(831.29, 777.82), weight: 25 }, { achieve: ar(38.59, 27.80), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "40100",
        name: "인재육성체계 통합관리 거버넌스 이행률",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(100, 100),
        targetValue: 100,
        actualValue: 100,
        unit: "%",
        trendData: [
          { year: 2022, target: 100, actual: 100 },
          { year: 2023, target: 100, actual: 100 },
          { year: 2024, target: 100, actual: 100 },
          { year: 2025, target: 90, actual: null },
          { year: 2026, target: 90, actual: null },
          { year: 2027, target: 90, actual: null },
        ],
        subIndicators: [
          {
            id: "40101",
            name: "거버넌스 활동 실행 건수(법령상 위원회)",
            description: "교무위원회·기획위원회 등 법령상 위원회의 학년도 내 실제 개최·운영 건수를 입력하세요.",
            variableKey: "A",
            deptName: "기획처",
            actualValue: 15,
            targetValue: 25,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "40102",
            name: "거버넌스 활동 계획 건수(법령상 위원회)",
            description: "법령상 위원회의 학년도 계획 개최·운영 건수를 입력하세요.",
            variableKey: "B",
            deptName: "기획처",
            actualValue: 15,
            targetValue: 25,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "40200",
        name: "교육과정 질 관리 인증 교과목 누적 비율",
        weight: 25,
        formula: "A / B",
        achieveRate: ar(26.94, 26.42),
        targetValue: 26.42,
        actualValue: 26.94,
        unit: "배",
        trendData: [
          { year: 2022, target: 26.42, actual: 22.98 },
          { year: 2023, target: 26.42, actual: 27.68 },
          { year: 2024, target: 26.42, actual: 26.94 },
          { year: 2025, target: 26, actual: null },
          { year: 2026, target: 26, actual: null },
          { year: 2027, target: 26, actual: null },
        ],
        subIndicators: [
          {
            id: "40201",
            name: "인증 누적 교과목 수(신규+유지)",
            description: "교육과정 질관리 인증을 획득하거나 유지 중인 누적 교과목 수(신규 취득 + 유지)를 입력하세요.",
            variableKey: "A",
            deptName: "교육인증센터",
            actualValue: 159,
            targetValue: 148,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "40202",
            name: "전임교원 평균 교과목 수(1·2학기 평균)",
            description: "전임교원 1인당 평균 담당 교과목 수(1학기·2학기 평균)를 입력하세요.",
            variableKey: "B",
            deptName: "학사지원팀",
            actualValue: 5.9,
            targetValue: 5.6,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "40300",
        name: "비교과 프로그램 참여율",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(831.29, 777.82),
        targetValue: 777.82,
        actualValue: 831.29,
        unit: "%",
        trendData: [
          { year: 2022, target: 777.82, actual: 842.17 },
          { year: 2023, target: 777.82, actual: 675.33 },
          { year: 2024, target: 777.82, actual: 831.29 },
          { year: 2025, target: 841, actual: null },
          { year: 2026, target: 900, actual: null },
          { year: 2027, target: 973, actual: null },
        ],
        subIndicators: [
          {
            id: "40301",
            name: "비교과 프로그램 참여 학생 수",
            description: "학년도 내 비교과 프로그램(튜터링·멘토링·특강·동아리 등)에 참여한 학생 수(중복 포함 연인원)를 입력하세요.",
            variableKey: "A",
            deptName: "비교과통합센터",
            actualValue: 41681,
            targetValue: 39000,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "40302",
            name: "학부 재학생 수(1·2학기 평균)",
            description: "학부 재학생 수 1·2학기 평균 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "학사지원팀",
            actualValue: 5014,
            targetValue: 5014,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "ENROLLED_STUDENTS_AVG",
          },
        ],
      },
      {
        id: "40400",
        name: "대학 교육이념 연계 인성교육 프로그램 참여 비율",
        weight: 25,
        formula: "(A + B + C) / D × 100",
        achieveRate: ar(38.59, 27.80),
        targetValue: 27.80,
        actualValue: 38.59,
        unit: "%",
        trendData: [
          { year: 2022, target: 27.80, actual: 27.18 },
          { year: 2023, target: 27.80, actual: 26.07 },
          { year: 2024, target: 27.80, actual: 38.59 },
          { year: 2025, target: 25, actual: null },
          { year: 2026, target: 30, actual: null },
          { year: 2027, target: 40, actual: null },
        ],
        subIndicators: [
          {
            id: "40401",
            name: "인성교육(비교과) 참여 학생 수 — 제자훈련·수련회",
            description: "제자훈련·수련회 등 교목처 주관 인성교육 비교과 프로그램 참여 학생 수(연인원)를 입력하세요.",
            variableKey: "A",
            deptName: "교목처",
            actualValue: 200,
            targetValue: 184,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "40402",
            name: "인성교육(비교과) 참여 학생 수 — 공동체리더·MVP+·Peoples 등",
            description: "공동체리더·MVP+·Peoples 등 리더십센터 주관 인성교육 비교과 프로그램 참여 학생 수(연인원)를 입력하세요.",
            variableKey: "B",
            deptName: "리더십센터",
            actualValue: 1735,
            targetValue: 1210,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "40403",
            name: "인성교육(교과) 참여 학생 수 — 리더십의이해·창의적문제해결",
            description: "리더십의이해·창의적문제해결 등 인성교육 교과목 수강 학생 수(연인원)를 입력하세요.",
            variableKey: "C",
            deptName: "리더십센터",
            actualValue: 0,
            targetValue: 0,
            unit: "명",
            status: "DRAFT",
            inputType: "MANUAL",
          },
          {
            id: "40404",
            name: "학부 재학생 수(1·2학기 평균)",
            description: "학부 재학생 수 1·2학기 평균 (시스템 자동 연동)",
            variableKey: "D",
            deptName: "학사지원팀",
            actualValue: 5014,
            targetValue: 5014,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "ENROLLED_STUDENTS_AVG",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 50000 · MVP 인재 성장 지수
  // 산출식: A×0.2 + B×0.2 + C×0.2 + D×0.2 + E×0.2
  // ═══════════════════════════════════════════════════════════
  {
    id: "50000",
    name: "MVP 인재 성장 지수",
    category: "Ⅴ. MVP 인재 성장",
    description:
      "학생역량증진 활동지수(A), 개별화 교육 지원(B), 학습역량강화 성장지수(C), 혁신형 프로그램 신규개발(D), 학업생활 만족도(E) 5개 지표 각 20%.",
    formula: "A×0.2 + B×0.2 + C×0.2 + D×0.2 + E×0.2",
    score: ws([
      { achieve: ar(8.054, 9.051), weight: 20 },
      { achieve: ar(211.52, 19.95), weight: 20 },
      { achieve: ar(37.82, 38.68), weight: 20 },
      { achieve: ar(3, 3), weight: 20 },
      { achieve: ar(75, 76), weight: 20 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 90, actual: ws([{ achieve: ar(9.48, 9.051), weight: 20 }, { achieve: ar(20.17, 19.95), weight: 20 }, { achieve: ar(39.09, 38.68), weight: 20 }, { achieve: ar(1, 3), weight: 20 }, { achieve: ar(77, 76), weight: 20 }]) },
      { year: 2023, target: 92, actual: ws([{ achieve: ar(7.85, 9.051), weight: 20 }, { achieve: ar(20.75, 19.95), weight: 20 }, { achieve: ar(38.26, 38.68), weight: 20 }, { achieve: ar(3, 3), weight: 20 }, { achieve: ar(76, 76), weight: 20 }]) },
      { year: 2024, target: 95, actual: ws([{ achieve: ar(8.054, 9.051), weight: 20 }, { achieve: ar(211.52, 19.95), weight: 20 }, { achieve: ar(37.82, 38.68), weight: 20 }, { achieve: ar(3, 3), weight: 20 }, { achieve: ar(75, 76), weight: 20 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "50100",
        name: "학생역량증진 활동지수",
        weight: 20,
        formula: "(A/B×100×0.4) + (C/B×100×0.6)",
        achieveRate: ar(8.054, 9.051),
        targetValue: 9.051,
        actualValue: 8.054,
        unit: "%",
        trendData: [
          { year: 2022, target: 9.051, actual: 9.48 },
          { year: 2023, target: 9.051, actual: 7.85 },
          { year: 2024, target: 9.051, actual: 8.054 },
          { year: 2025, target: 8.87, actual: null },
          { year: 2026, target: 8.96, actual: null },
          { year: 2027, target: 9.05, actual: null },
        ],
        subIndicators: [
          {
            id: "50101",
            name: "성장형 학습역량 프로그램 참여자(SU-EBE, 학습법 특강)",
            description: "SU-EBE 프로그램·학습법 특강 등 성장형 학습역량 프로그램 참여 학생 수(연인원)를 입력하세요.",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 837,
            targetValue: 1537,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50103",
            name: "해당년도 재학생 수",
            description: "해당 학년도 재학생 수 (시스템 자동 연동)",
            variableKey: "B",
            deptName: "학사지원팀",
            actualValue: 10027,
            targetValue: 10027,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "ENROLLED_STUDENTS",
          },
          {
            id: "50102",
            name: "협력형 학습역량 프로그램 참여자(학습공동체·삼육메이트)",
            description: "학습공동체·삼육메이트 등 협력형 학습역량 프로그램 참여 학생 수(연인원)를 입력하세요.",
            variableKey: "C",
            deptName: "교수학습개발센터",
            actualValue: 788,
            targetValue: 488,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "50200",
        name: "학생 1인당 개별화 교육 지원 건수",
        weight: 20,
        formula: "(A + B) / C × 100",
        achieveRate: ar(211.52, 19.95),
        targetValue: 19.95,
        actualValue: 211.52,
        unit: "%",
        trendData: [
          { year: 2022, target: 19.95, actual: 20.17 },
          { year: 2023, target: 19.95, actual: 20.75 },
          { year: 2024, target: 19.95, actual: 211.52 },
          { year: 2025, target: 19.46, actual: null },
          { year: 2026, target: 19.56, actual: null },
          { year: 2027, target: 19.65, actual: null },
        ],
        subIndicators: [
          {
            id: "50201",
            name: "정서·심리 프로그램 참여자 수",
            description: "정서·심리 상담 및 프로그램(집단상담·심리검사·위기지원 등) 참여 학생 수(연인원)를 입력하세요.",
            variableKey: "A",
            deptName: "학생상담센터",
            actualValue: 23,
            targetValue: 2000,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50202",
            name: "진로 및 취업 상담 및 프로그램 참여자수",
            description: "진로·취업 상담 및 취업 프로그램(취업특강·모의면접·인턴십 등) 참여자 수(연인원)를 입력하세요.",
            variableKey: "B",
            deptName: "취업진로지원센터",
            actualValue: 21186,
            targetValue: null as unknown as number,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50203",
            name: "재학생 수",
            description: "재학생 수 (시스템 자동 연동)",
            variableKey: "C",
            deptName: "학사지원팀",
            actualValue: 10027,
            targetValue: 10027,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MASTER_AUTO",
            masterCode: "ENROLLED_STUDENTS",
          },
        ],
      },
      {
        id: "50300",
        name: "학습역량강화 성장지수",
        weight: 20,
        formula: "(A+B)/2×0.5 + (C+D)/2×0.5",
        achieveRate: ar(37.82, 38.68),
        targetValue: 38.68,
        actualValue: 37.82,
        unit: "점",
        trendData: [
          { year: 2022, target: 38.68, actual: 39.09 },
          { year: 2023, target: 38.68, actual: 38.26 },
          { year: 2024, target: 38.68, actual: 37.82 },
          { year: 2025, target: 38.90, actual: null },
          { year: 2026, target: 39.50, actual: null },
          { year: 2027, target: 40.00, actual: null },
        ],
        subIndicators: [
          {
            id: "50301",
            name: "학습참여 — 협력학습",
            description: "학습역량 진단도구 내 '협력학습' 항목 점수를 입력하세요. (설문 진단 결과 점수)",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 36.88,
            targetValue: 38.71,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50302",
            name: "학습참여 — 자기주도학습",
            description: "학습역량 진단도구 내 '자기주도학습' 항목 점수를 입력하세요. (설문 진단 결과 점수)",
            variableKey: "B",
            deptName: "교수학습개발센터",
            actualValue: 38.22,
            targetValue: 38.51,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50303",
            name: "학습자심리 — 학업적자기효능감",
            description: "학습자심리 진단도구 내 '학업적자기효능감' 항목 점수를 입력하세요. (설문 진단 결과 점수)",
            variableKey: "C",
            deptName: "교수학습개발센터",
            actualValue: 37.6,
            targetValue: 39.38,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50304",
            name: "학습자심리 — 학업동기",
            description: "학습자심리 진단도구 내 '학업동기' 항목 점수를 입력하세요. (설문 진단 결과 점수)",
            variableKey: "D",
            deptName: "교수학습개발센터",
            actualValue: 38.58,
            targetValue: 38.1,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "50400",
        name: "혁신형 학습역량·정서심리 프로그램 신규개발 수",
        weight: 20,
        formula: "A + B",
        achieveRate: ar(3, 3),
        targetValue: 3,
        actualValue: 3,
        unit: "건",
        trendData: [
          { year: 2022, target: 3, actual: 1 },
          { year: 2023, target: 3, actual: 3 },
          { year: 2024, target: 3, actual: 3 },
          { year: 2025, target: 6, actual: null },
          { year: 2026, target: 7, actual: null },
          { year: 2027, target: 8, actual: null },
        ],
        subIndicators: [
          {
            id: "50401",
            name: "혁신학습법 특강 건수(에듀테크·생성형AI 관련)",
            description: "에듀테크·생성형AI 등을 활용한 혁신학습법 특강 개최 건수를 입력하세요.",
            variableKey: "A",
            deptName: "교수학습개발센터",
            actualValue: 0,
            targetValue: 0,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50402",
            name: "XR 등 에듀테크 기반 정서심리프로그램 개발건수(누적)",
            description: "XR·메타버스 등 에듀테크 기반 정서심리 프로그램 신규 개발 건수(누적)를 입력하세요.",
            variableKey: "B",
            deptName: "학생상담센터",
            actualValue: 3,
            targetValue: 3,
            unit: "건",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "50500",
        name: "학생 학업생활 만족도",
        weight: 20,
        formula: "(A + B + C) / 3",
        achieveRate: ar(75, 76),
        targetValue: 76,
        actualValue: 75,
        unit: "%",
        trendData: [
          { year: 2022, target: 76, actual: 77 },
          { year: 2023, target: 76, actual: 76 },
          { year: 2024, target: 76, actual: 75 },
          { year: 2025, target: 78, actual: null },
          { year: 2026, target: 79, actual: null },
          { year: 2027, target: 80, actual: null },
        ],
        subIndicators: [
          {
            id: "50501",
            name: "교육환경 만족도 점수",
            description: "강의실·실험실·도서관 등 교육환경에 대한 학생 만족도 설문 결과 점수를 입력하세요. (100점 만점)",
            variableKey: "A",
            deptName: "시설관리팀",
            actualValue: 65.72,
            targetValue: 71.5,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50502",
            name: "학생복지 만족도 점수",
            description: "장학·식당·기숙사 등 학생복지에 대한 만족도 설문 결과 점수를 입력하세요. (100점 만점)",
            variableKey: "B",
            deptName: "학생복지팀",
            actualValue: 70.29,
            targetValue: 71,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
          {
            id: "50503",
            name: "생활교육원 만족도 점수",
            description: "기숙사·멘토링 등 생활교육원 운영에 대한 만족도 설문 결과 점수를 입력하세요. (100점 만점)",
            variableKey: "C",
            deptName: "생활교육원",
            actualValue: 90.3,
            targetValue: 85,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 60000 · MVP 인재 사회기여 역량 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "60000",
    name: "MVP 인재 사회기여 역량 지수",
    category: "Ⅵ. MVP 인재 사회기여 역량",
    description:
      "진로·취창업 프로그램 개발·개편 비율(A), 혁신형 프로그램 신규개발(B), 취창업 교과목 운영(C), MVP 인증 학생 비율(D) 4개 지표 각 25%.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(34, 36), weight: 25 },
      { achieve: ar(2, 2), weight: 25 },
      { achieve: ar(39, 36), weight: 25 },
      { achieve: ar(1.12, 1.89), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 85, actual: ws([{ achieve: ar(32, 36), weight: 25 }, { achieve: ar(1, 2), weight: 25 }, { achieve: ar(45, 36), weight: 25 }, { achieve: ar(1.71, 1.89), weight: 25 }]) },
      { year: 2023, target: 88, actual: ws([{ achieve: ar(35, 36), weight: 25 }, { achieve: ar(2, 2), weight: 25 }, { achieve: ar(42, 36), weight: 25 }, { achieve: ar(2.13, 1.89), weight: 25 }]) },
      { year: 2024, target: 90, actual: ws([{ achieve: ar(34, 36), weight: 25 }, { achieve: ar(2, 2), weight: 25 }, { achieve: ar(39, 36), weight: 25 }, { achieve: ar(1.12, 1.89), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "60100",
        name: "진로·취창업 프로그램 개발·개편 비율",
        weight: 25,
        formula: "(A + B) / (C + D) × 100",
        achieveRate: ar(34, 36),
        targetValue: 36,
        actualValue: 34,
        unit: "%",
        trendData: [
          { year: 2022, target: 36, actual: 32 },
          { year: 2023, target: 36, actual: 35 },
          { year: 2024, target: 36, actual: 34 },
          { year: 2025, target: 45, actual: null },
          { year: 2026, target: 46, actual: null },
          { year: 2027, target: 46, actual: null },
        ],
        subIndicators: [
          { id: "60101", name: "개발·개편 진로·취업 프로그램 수", description: "학년도 내 신규 개발 또는 대폭 개편된 진로·취업 프로그램 수를 입력하세요.", variableKey: "A", deptName: "취업진로지원센터", actualValue: 19, targetValue: 19, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "60102", name: "개발·개편 창업 프로그램 수", description: "학년도 내 신규 개발 또는 대폭 개편된 창업 지원 프로그램 수를 입력하세요.", variableKey: "B", deptName: "스타트업지원센터", actualValue: 23, targetValue: 21, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "60103", name: "학년도별 개설 프로그램 수(진로·취업)", description: "학년도 전체 개설 진로·취업 프로그램 수를 입력하세요.", variableKey: "C", deptName: "취업진로지원센터", actualValue: 73, targetValue: 71, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "60104", name: "학년도별 개설 프로그램 수(창업)", description: "학년도 전체 개설 창업 지원 프로그램 수를 입력하세요.", variableKey: "D", deptName: "스타트업지원센터", actualValue: 49, targetValue: 39, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "60200",
        name: "혁신형 진로·취창업 프로그램 신규개발 수",
        weight: 25,
        formula: "A",
        achieveRate: ar(2, 2),
        targetValue: 2,
        actualValue: 2,
        unit: "건",
        trendData: [
          { year: 2022, target: 2, actual: 1 },
          { year: 2023, target: 2, actual: 2 },
          { year: 2024, target: 2, actual: 2 },
          { year: 2025, target: 3, actual: null },
          { year: 2026, target: 3, actual: null },
          { year: 2027, target: 4, actual: null },
        ],
        subIndicators: [
          { id: "60201", name: "XR 등 에듀테크 기반 진로·취창업 프로그램 개발(진로·취업)", description: "XR·메타버스·AI 등 에듀테크 기반으로 신규 개발한 진로·취창업 프로그램 건수를 입력하세요.", variableKey: "A", deptName: "취업진로지원센터", actualValue: 2, targetValue: 2, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "60300",
        name: "진로개발 및 창업 지원 교과목 운영 건수",
        weight: 25,
        formula: "A + B",
        achieveRate: ar(39, 36),
        targetValue: 36,
        actualValue: 39,
        unit: "건",
        trendData: [
          { year: 2022, target: 36, actual: 45 },
          { year: 2023, target: 36, actual: 42 },
          { year: 2024, target: 36, actual: 39 },
          { year: 2025, target: 41, actual: null },
          { year: 2026, target: 42, actual: null },
          { year: 2027, target: 43, actual: null },
        ],
        subIndicators: [
          { id: "60301", name: "진로개발 교과목(교양·전공) 개설 건수", description: "학년도 내 개설된 진로개발 교과목(교양+전공) 총 건수를 입력하세요.", variableKey: "A", deptName: "취업진로지원센터", actualValue: 19, targetValue: 18, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "60302", name: "창업 교과목 개설 건수", description: "학년도 내 개설된 창업 관련 교과목 총 건수를 입력하세요.", variableKey: "B", deptName: "스타트업지원센터", actualValue: 20, targetValue: 18, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "60400",
        name: "삼육 MVP 인증획득 학생 비율",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(1.12, 1.89),
        targetValue: 1.89,
        actualValue: 1.12,
        unit: "%",
        trendData: [
          { year: 2022, target: 1.89, actual: 1.71 },
          { year: 2023, target: 1.89, actual: 2.13 },
          { year: 2024, target: 1.89, actual: 1.12 },
          { year: 2025, target: 2.30, actual: null },
          { year: 2026, target: 2.40, actual: null },
          { year: 2027, target: 2.50, actual: null },
        ],
        subIndicators: [
          { id: "60401", name: "MVP 인증 1개 이상 획득 졸업생 수", description: "삼육MVP 인증(학습·리더십·봉사·창업 등) 1개 이상 획득하고 졸업한 학생 수를 입력하세요.", variableKey: "A", deptName: "비교과통합센터", actualValue: 14, targetValue: 25, unit: "명", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "60402", name: "학년도별 졸업생 수", description: "학년도 졸업생 수 (시스템 자동 연동)", variableKey: "B", deptName: "학사지원팀", actualValue: 1247, targetValue: 1322, unit: "명", status: "SUBMITTED", inputType: "MASTER_AUTO", masterCode: "GRADUATES" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 70000 · 사회가치 창출 연구역량 강화 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "70000",
    name: "사회가치 창출 연구역량 강화 지수",
    category: "Ⅶ. 사회가치 창출 연구역량 강화",
    description:
      "전임교원 1인당 국제논문 수(A), 연구역량 강화 이행률(B), 학제간·국제 융합연구 건수(C), 대학원 교육 혁신 건수(D) 4개 지표 각 25%.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(0.3774, 0.2876), weight: 25 },
      { achieve: ar(100, 100), weight: 25 },
      { achieve: ar(8.64, 7.80), weight: 25 },
      { achieve: ar(13, 18), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 90, actual: ws([{ achieve: ar(0.2765, 0.2876), weight: 25 }, { achieve: ar(100, 100), weight: 25 }, { achieve: ar(0, 7.80), weight: 25 }, { achieve: ar(15, 18), weight: 25 }]) },
      { year: 2023, target: 92, actual: ws([{ achieve: ar(0.2763, 0.2876), weight: 25 }, { achieve: ar(100, 100), weight: 25 }, { achieve: ar(6.80, 7.80), weight: 25 }, { achieve: ar(16, 18), weight: 25 }]) },
      { year: 2024, target: 95, actual: ws([{ achieve: ar(0.3774, 0.2876), weight: 25 }, { achieve: ar(100, 100), weight: 25 }, { achieve: ar(8.64, 7.80), weight: 25 }, { achieve: ar(13, 18), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "70100",
        name: "전임교원 1인당 국제논문 수",
        weight: 25,
        formula: "A",
        achieveRate: ar(0.3774, 0.2876),
        targetValue: 0.2876,
        actualValue: 0.3774,
        unit: "편/인",
        trendData: [
          { year: 2022, target: 0.2876, actual: 0.2765 },
          { year: 2023, target: 0.2876, actual: 0.2763 },
          { year: 2024, target: 0.2876, actual: 0.3774 },
          { year: 2025, target: 0.2933, actual: null },
          { year: 2026, target: 0.2991, actual: null },
          { year: 2027, target: 0.3050, actual: null },
        ],
        subIndicators: [
          {
            id: "70101",
            name: "전임교원 1인당 국제논문(SCI/SSCI/A&HCI) 수",
            description: "학년도 전임교원 1인당 국제학술지(SCI·SSCI·A&HCI 등 등재) 게재 논문 편수를 입력하세요. (연구산학처 집계 기준)",
            variableKey: "A",
            deptName: "연구산학처",
            actualValue: 0.3774,
            targetValue: 0.2876,
            unit: "편/인",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "70200",
        name: "연구역량 강화 개선계획 이행률",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(100, 100),
        targetValue: 100,
        actualValue: 100,
        unit: "%",
        trendData: [
          { year: 2022, target: 100, actual: 100 },
          { year: 2023, target: 100, actual: 100 },
          { year: 2024, target: 100, actual: 100 },
          { year: 2025, target: 100, actual: null },
          { year: 2026, target: 100, actual: null },
          { year: 2027, target: 100, actual: null },
        ],
        subIndicators: [
          { id: "70201", name: "연구역량강화 이행 건수(연구관련 규정개정)", description: "연구관련 규정 개정·제정 등 연구역량강화 계획 중 실제 이행한 건수를 입력하세요.", variableKey: "A", deptName: "연구산학처", actualValue: 4, targetValue: 4, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "70202", name: "연구역량강화 계획 건수(연구관련 규정개정)", description: "연구관련 규정 개정·제정 등 연구역량강화 계획 총 건수를 입력하세요.", variableKey: "B", deptName: "연구산학처", actualValue: 4, targetValue: 4, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "70300",
        name: "학제간 및 국제 융합연구 수행 건수",
        weight: 25,
        formula: "A / 전체 국제논문 수 × 100",
        achieveRate: ar(8.64, 7.80),
        targetValue: 7.80,
        actualValue: 8.64,
        unit: "%",
        trendData: [
          { year: 2022, target: 7.80, actual: 0 },
          { year: 2023, target: 7.80, actual: 6.80 },
          { year: 2024, target: 7.80, actual: 8.64 },
          { year: 2025, target: 11.02, actual: null },
          { year: 2026, target: 11.24, actual: null },
          { year: 2027, target: 11.46, actual: null },
        ],
        subIndicators: [
          {
            id: "70301",
            name: "학제간·국제 공동 연구 논문 수",
            description: "2개 이상 학문 분야가 결합된 학제간 연구 또는 외국 기관과 공동 수행한 국제 융합연구 논문 수를 입력하세요.",
            variableKey: "A",
            deptName: "연구산학처",
            actualValue: 8.64,
            targetValue: 7.80,
            unit: "%",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "70400",
        name: "대학원 교육 혁신 건수",
        weight: 25,
        formula: "A + B + C",
        achieveRate: ar(13, 18),
        targetValue: 18,
        actualValue: 13,
        unit: "건",
        trendData: [
          { year: 2022, target: 18, actual: 15 },
          { year: 2023, target: 18, actual: 16 },
          { year: 2024, target: 18, actual: 13 },
          { year: 2025, target: 19, actual: null },
          { year: 2026, target: 20, actual: null },
          { year: 2027, target: 23, actual: null },
        ],
        subIndicators: [
          { id: "70401", name: "교과 혁신건수", description: "대학원 교육과정 개편·혁신 건수(신규 교과목 개설, 기존 교과목 대폭 개편 포함)를 입력하세요.", variableKey: "A", deptName: "대학원교학부", actualValue: 1, targetValue: 2, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "70402", name: "비교과 프로그램 수", description: "대학원 비교과 프로그램(세미나·특강·연구지원 등) 운영 건수를 입력하세요.", variableKey: "B", deptName: "대학원교학부", actualValue: 5, targetValue: 5, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "70403", name: "영어트랙 건수", description: "영어로 운영되는 대학원 교과목 또는 프로그램(영어트랙) 건수를 입력하세요.", variableKey: "C", deptName: "대학원교학부", actualValue: 7, targetValue: 15, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 80000 · 사회 가치창출 공유·협력 혁신 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "80000",
    name: "사회 가치창출 공유·협력 혁신 지수",
    category: "Ⅷ. 사회가치 창출 공유·협력 혁신",
    description:
      "서비스러닝 교육 만족도(A), 대외협력 협약 체결(B), 평생교육 프로그램 참여자(C), 교육국제화 참여 학생 비율(D) 4개 지표 각 25%.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(94.91, 90), weight: 25 },
      { achieve: ar(6, 13), weight: 25 },
      { achieve: ar(6892, 11084), weight: 25 },
      { achieve: ar(0.38, 0.78), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 80, actual: ws([{ achieve: ar(0, 90), weight: 25 }, { achieve: ar(7, 13), weight: 25 }, { achieve: ar(10974, 11084), weight: 25 }, { achieve: ar(1.50, 0.78), weight: 25 }]) },
      { year: 2023, target: 85, actual: ws([{ achieve: ar(92.08, 90), weight: 25 }, { achieve: ar(10, 13), weight: 25 }, { achieve: ar(11029, 11084), weight: 25 }, { achieve: ar(0.80, 0.78), weight: 25 }]) },
      { year: 2024, target: 90, actual: ws([{ achieve: ar(94.91, 90), weight: 25 }, { achieve: ar(6, 13), weight: 25 }, { achieve: ar(6892, 11084), weight: 25 }, { achieve: ar(0.38, 0.78), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "80100",
        name: "서비스러닝 교육 만족도",
        weight: 25,
        formula: "(A + B) / 2",
        achieveRate: ar(94.91, 90),
        targetValue: 90,
        actualValue: 94.91,
        unit: "점",
        trendData: [
          { year: 2022, target: 90, actual: 0 },
          { year: 2023, target: 90, actual: 92.08 },
          { year: 2024, target: 90, actual: 94.91 },
          { year: 2025, target: 90, actual: null },
          { year: 2026, target: 84.9, actual: null },
          { year: 2027, target: 88.8, actual: null },
        ],
        subIndicators: [
          { id: "80101", name: "서비스러닝 교과목 이수자 만족도", description: "서비스러닝 교과목 이수 학생 만족도 설문 결과 점수를 입력하세요. (100점 만점)", variableKey: "A", deptName: "사회봉사단", actualValue: 95, targetValue: 90, unit: "점", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "80102", name: "서비스러닝 비교과 프로그램 이수자 만족도", description: "서비스러닝 비교과 프로그램 이수 학생 만족도 설문 결과 점수를 입력하세요. (100점 만점)", variableKey: "B", deptName: "사회봉사단", actualValue: 94.81, targetValue: 90, unit: "점", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "80200",
        name: "대외협력 협약 체결 건수",
        weight: 25,
        formula: "A + B",
        achieveRate: ar(6, 13),
        targetValue: 13,
        actualValue: 6,
        unit: "건",
        trendData: [
          { year: 2022, target: 13, actual: 7 },
          { year: 2023, target: 13, actual: 10 },
          { year: 2024, target: 13, actual: 6 },
          { year: 2025, target: 16, actual: null },
          { year: 2026, target: 20, actual: null },
          { year: 2027, target: 22, actual: null },
        ],
        subIndicators: [
          { id: "80201", name: "지역사회 발전 관련 협력체결(신규+계속)", description: "지역사회 발전 관련 기관과 체결한 협약 건수(신규 협약 + 계속 협약)를 입력하세요.", variableKey: "A", deptName: "대외협력팀", actualValue: 5, targetValue: 7, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "80202", name: "대학간 공유협력 관련 협력체결(신규+계속)", description: "타 대학과의 공유·협력 관련 협약 체결 건수(신규 협약 + 계속 협약)를 입력하세요.", variableKey: "B", deptName: "대외협력팀", actualValue: 1, targetValue: 6, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "80300",
        name: "평생교육 프로그램 참여자 수",
        weight: 25,
        formula: "A",
        achieveRate: ar(6892, 11084),
        targetValue: 11084,
        actualValue: 6892,
        unit: "명",
        trendData: [
          { year: 2022, target: 11084, actual: 10974 },
          { year: 2023, target: 11084, actual: 11029 },
          { year: 2024, target: 11084, actual: 6892 },
          { year: 2025, target: 11139, actual: null },
          { year: 2026, target: 11195, actual: null },
          { year: 2027, target: 11249, actual: null },
        ],
        subIndicators: [
          {
            id: "80301",
            name: "평생교육원 프로그램 참여자 수(연인원)",
            description: "학년도 내 평생교육원 강좌·프로그램에 수강·참여한 인원 총합(연인원)을 입력하세요.",
            variableKey: "A",
            deptName: "평생교육원",
            actualValue: 6892,
            targetValue: 11084,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "80400",
        name: "SU-edx 교육국제화 프로그램 참여 학생 비율",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(0.38, 0.78),
        targetValue: 0.78,
        actualValue: 0.38,
        unit: "%",
        trendData: [
          { year: 2022, target: 0.78, actual: 1.50 },
          { year: 2023, target: 0.78, actual: 0.80 },
          { year: 2024, target: 0.78, actual: 0.38 },
          { year: 2025, target: 1.12, actual: null },
          { year: 2026, target: 1.32, actual: null },
          { year: 2027, target: 7.50, actual: null },
        ],
        subIndicators: [
          { id: "80401", name: "단기 국제교류 참여학생 수(어학연수·학점교류·비교과)", description: "어학연수·학점교류·비교과 국제프로그램 등 단기 국제교류 참여 학생 수(연인원)를 입력하세요.", variableKey: "A", deptName: "국제교육원", actualValue: 38, targetValue: 78, unit: "명", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "80402", name: "재학생 수", description: "재학생 수 (시스템 자동 연동)", variableKey: "B", deptName: "학사지원팀", actualValue: 10027, targetValue: 10027, unit: "명", status: "SUBMITTED", inputType: "MASTER_AUTO", masterCode: "ENROLLED_STUDENTS" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 90000 · 사회가치 창출 산학협력 혁신 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "90000",
    name: "사회가치 창출 산학협력 혁신 지수",
    category: "Ⅸ. 사회가치 창출 산학협력 혁신",
    description:
      "산학연계교육 참여자 비율(A), 산학협력 가족회사 확보(B), 산업체 만족도(C), 산학협력 역량강화 이행률(D) 4개 지표 각 25%.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(18.19, 11.05), weight: 25 },
      { achieve: ar(432, 516), weight: 25 },
      { achieve: ar(69.61, 74), weight: 25 },
      { achieve: ar(87, 100), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 90, actual: ws([{ achieve: ar(11.61, 11.05), weight: 25 }, { achieve: ar(400, 516), weight: 25 }, { achieve: ar(72, 74), weight: 25 }, { achieve: ar(100, 100), weight: 25 }]) },
      { year: 2023, target: 92, actual: ws([{ achieve: ar(18.88, 11.05), weight: 25 }, { achieve: ar(410, 516), weight: 25 }, { achieve: ar(73, 74), weight: 25 }, { achieve: ar(100, 100), weight: 25 }]) },
      { year: 2024, target: 95, actual: ws([{ achieve: ar(18.19, 11.05), weight: 25 }, { achieve: ar(432, 516), weight: 25 }, { achieve: ar(69.61, 74), weight: 25 }, { achieve: ar(87, 100), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "90100",
        name: "산학연계교육 참여자 비율",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(18.19, 11.05),
        targetValue: 11.05,
        actualValue: 18.19,
        unit: "%",
        trendData: [
          { year: 2022, target: 11.05, actual: 11.61 },
          { year: 2023, target: 11.05, actual: 18.88 },
          { year: 2024, target: 11.05, actual: 18.19 },
          { year: 2025, target: 16, actual: null },
          { year: 2026, target: 18, actual: null },
          { year: 2027, target: 20, actual: null },
        ],
        subIndicators: [
          { id: "90101", name: "산학협력 연계교육 참여 학생 수(캡스톤디자인 등)", description: "캡스톤디자인·현장실습·인턴십 등 산학협력 연계교육에 참여한 학생 수(연인원)를 입력하세요.", variableKey: "A", deptName: "학사지원팀", actualValue: 1824, targetValue: 1108, unit: "명", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "90102", name: "재학생 수", description: "재학생 수 (시스템 자동 연동)", variableKey: "B", deptName: "학사지원팀", actualValue: 10027, targetValue: 10027, unit: "명", status: "SUBMITTED", inputType: "MASTER_AUTO", masterCode: "ENROLLED_STUDENTS" },
        ],
      },
      {
        id: "90200",
        name: "산학협력 가족회사 확보 건수",
        weight: 25,
        formula: "A",
        achieveRate: ar(432, 516),
        targetValue: 516,
        actualValue: 432,
        unit: "개",
        trendData: [
          { year: 2022, target: 516, actual: 400 },
          { year: 2023, target: 516, actual: 410 },
          { year: 2024, target: 516, actual: 432 },
          { year: 2025, target: 530, actual: null },
          { year: 2026, target: 540, actual: null },
          { year: 2027, target: 550, actual: null },
        ],
        subIndicators: [
          {
            id: "90201",
            name: "산학협력 가족회사 확보 수",
            description: "학년도 말 기준 산학협력 가족회사로 등록된 기업 수를 입력하세요. (신규 + 계속 유지 기업 합계)",
            variableKey: "A",
            deptName: "산학협력단",
            actualValue: 432,
            targetValue: 516,
            unit: "개",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "90300",
        name: "산업체 만족도",
        weight: 25,
        formula: "A",
        achieveRate: ar(69.61, 74),
        targetValue: 74,
        actualValue: 69.61,
        unit: "점",
        trendData: [
          { year: 2022, target: 74, actual: 72 },
          { year: 2023, target: 74, actual: 73 },
          { year: 2024, target: 74, actual: 69.61 },
          { year: 2025, target: 74, actual: null },
          { year: 2026, target: 75, actual: null },
          { year: 2027, target: 75, actual: null },
        ],
        subIndicators: [
          {
            id: "90301",
            name: "산업체(가족회사) 대학교육 만족도",
            description: "산학협력 가족회사를 대상으로 실시한 대학교육 만족도 설문 결과 점수를 입력하세요. (100점 만점)",
            variableKey: "A",
            deptName: "산학협력단",
            actualValue: 69.61,
            targetValue: 74,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "90400",
        name: "산학협력 역량강화 개선과제 이행률",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(87, 100),
        targetValue: 100,
        actualValue: 87,
        unit: "%",
        trendData: [
          { year: 2022, target: 100, actual: 100 },
          { year: 2023, target: 100, actual: 100 },
          { year: 2024, target: 100, actual: 87 },
          { year: 2025, target: 90, actual: null },
          { year: 2026, target: 90, actual: null },
          { year: 2027, target: 90, actual: null },
        ],
        subIndicators: [
          { id: "90401", name: "산학협력 역량강화 활동 이행 건수", description: "산학협력단 역량강화 계획 중 실제 이행한 활동 건수를 입력하세요.", variableKey: "A", deptName: "산학협력단", actualValue: 78, targetValue: 95, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "90402", name: "산학협력 역량강화 활동 계획 건수", description: "산학협력단 역량강화 계획 총 활동 건수를 입력하세요.", variableKey: "B", deptName: "산학협력단", actualValue: 90, targetValue: 95, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 91000 · 적정 규모화 관리 지수
  // 산출식: A×0.5 + B×0.5
  // ═══════════════════════════════════════════════════════════
  {
    id: "91000",
    name: "적정 규모화 관리 지수",
    category: "Ⅹ. 적정 규모화 관리",
    description:
      "신입생 교육 만족도(A·50%), 외국인 유학생 수(B·50%) 2개 지표를 각 50%씩 합산합니다.",
    formula: "A×0.5 + B×0.5",
    score: ws([
      { achieve: ar(66.89, 67.6), weight: 50 },
      { achieve: ar(608, 1400), weight: 50 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 85, actual: ws([{ achieve: ar(65, 67.6), weight: 50 }, { achieve: ar(1100, 1400), weight: 50 }]) },
      { year: 2023, target: 88, actual: ws([{ achieve: ar(66.3, 67.6), weight: 50 }, { achieve: ar(1300, 1400), weight: 50 }]) },
      { year: 2024, target: 90, actual: ws([{ achieve: ar(66.89, 67.6), weight: 50 }, { achieve: ar(608, 1400), weight: 50 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "91100",
        name: "신입생 교육 만족도",
        weight: 50,
        formula: "A",
        achieveRate: ar(66.89, 67.6),
        targetValue: 67.6,
        actualValue: 66.89,
        unit: "점",
        trendData: [
          { year: 2022, target: 67.6, actual: 65 },
          { year: 2023, target: 67.6, actual: 66.3 },
          { year: 2024, target: 67.6, actual: 66.89 },
          { year: 2025, target: 69, actual: null },
          { year: 2026, target: 70.4, actual: null },
          { year: 2027, target: 71.8, actual: null },
        ],
        subIndicators: [
          {
            id: "91101",
            name: "신입생 교육(오리엔테이션·새내기세미나 등) 만족도",
            description: "신입생 오리엔테이션·새내기세미나 등 신입생 교육 프로그램에 대한 만족도 설문 결과 점수를 입력하세요. (100점 만점)",
            variableKey: "A",
            deptName: "학생지원팀",
            actualValue: 66.89,
            targetValue: 67.6,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "91200",
        name: "외국인 유학생 수",
        weight: 50,
        formula: "A",
        achieveRate: ar(608, 1400),
        targetValue: 1400,
        actualValue: 608,
        unit: "명",
        trendData: [
          { year: 2022, target: 1400, actual: 1100 },
          { year: 2023, target: 1400, actual: 1300 },
          { year: 2024, target: 1400, actual: 608 },
          { year: 2025, target: 1500, actual: null },
          { year: 2026, target: 1600, actual: null },
          { year: 2027, target: 1800, actual: null },
        ],
        subIndicators: [
          {
            id: "91201",
            name: "외국인 유학생 재학 인원",
            description: "학년도 기준 재학 중인 외국인 유학생 총 인원(학부+대학원)을 입력하세요.",
            variableKey: "A",
            deptName: "국제교육원",
            actualValue: 608,
            targetValue: 1400,
            unit: "명",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 100000 · 재정 건전성 확보 지수
  // 산출식: A×0.25 + B×0.25 + C×0.25 + D×0.25
  // ═══════════════════════════════════════════════════════════
  {
    id: "100000",
    name: "재정 건전성 확보 지수",
    category: "Ⅺ. 재정 건전성 확보",
    description:
      "재정수입 확충 이행률(A), 등록금 외 수입 목표 달성률(B), 기부금 수입 목표 달성률(C), 예산 집행률(D) 4개 지표 각 25%.",
    formula: "A×0.25 + B×0.25 + C×0.25 + D×0.25",
    score: ws([
      { achieve: ar(60, 68), weight: 25 },
      { achieve: ar(81.15, 82.50), weight: 25 },
      { achieve: ar(219.50, 100), weight: 25 },
      { achieve: ar(99, 95), weight: 25 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 90, actual: ws([{ achieve: ar(80, 68), weight: 25 }, { achieve: ar(78.65, 82.50), weight: 25 }, { achieve: ar(100, 100), weight: 25 }, { achieve: ar(95, 95), weight: 25 }]) },
      { year: 2023, target: 92, actual: ws([{ achieve: ar(74, 68), weight: 25 }, { achieve: ar(77.45, 82.50), weight: 25 }, { achieve: ar(100, 100), weight: 25 }, { achieve: ar(95, 95), weight: 25 }]) },
      { year: 2024, target: 95, actual: ws([{ achieve: ar(60, 68), weight: 25 }, { achieve: ar(81.15, 82.50), weight: 25 }, { achieve: ar(219.50, 100), weight: 25 }, { achieve: ar(99, 95), weight: 25 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "100100",
        name: "재정수입 확충 계획 이행률",
        weight: 25,
        formula: "이행건수 합계 / 계획건수 합계 × 100",
        achieveRate: ar(60, 68),
        targetValue: 68,
        actualValue: 60,
        unit: "%",
        trendData: [
          { year: 2022, target: 68, actual: 80 },
          { year: 2023, target: 68, actual: 74 },
          { year: 2024, target: 68, actual: 60 },
          { year: 2025, target: 90, actual: null },
          { year: 2026, target: 90, actual: null },
          { year: 2027, target: 90, actual: null },
        ],
        subIndicators: [
          { id: "100101", name: "이행건수 — 외국인학생유치", description: "외국인 유학생 유치 관련 활동(학생 수, 홍보, 협약 등) 이행 건수를 입력하세요.", variableKey: "A", deptName: "국제교육원", actualValue: 0, targetValue: 1402, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100102", name: "이행건수 — 평생교육 활성화", description: "평생교육원 프로그램·강좌 수강생 수(연인원)를 입력하세요.", variableKey: "B", deptName: "평생교육원", actualValue: 1278, targetValue: 1071, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100103", name: "이행건수 — 체육문화원 활성화", description: "체육문화센터 시설·프로그램 이용 건수(연인원)를 입력하세요.", variableKey: "C", deptName: "체육문화센터", actualValue: 5614, targetValue: 13812, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100106", name: "이행건수 — 국고활성화(취업진로)", description: "국고 지원 취업진로 관련 사업 이행 건수를 입력하세요.", variableKey: "F", deptName: "취업진로지원센터", actualValue: 8, targetValue: 6, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100107", name: "이행건수 — 국고활성화(스타트업)", description: "국고 지원 스타트업·창업 관련 사업 이행 건수를 입력하세요.", variableKey: "G", deptName: "스타트업지원센터", actualValue: 1, targetValue: 1, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100111", name: "이행건수 — 교육자산활용(공통기기)", description: "공통기기실험실 교육자산 활용 이행 건수(장비 활용·임대 등)를 입력하세요.", variableKey: "K", deptName: "공통기기실험실", actualValue: 0, targetValue: 100, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "100200",
        name: "등록금 외 수입(중장기) 목표 달성률",
        weight: 25,
        formula: "(A + B) / 2",
        achieveRate: ar(81.15, 82.50),
        targetValue: 82.50,
        actualValue: 81.15,
        unit: "%",
        trendData: [
          { year: 2022, target: 82.50, actual: 78.65 },
          { year: 2023, target: 82.50, actual: 77.45 },
          { year: 2024, target: 82.50, actual: 81.15 },
          { year: 2025, target: 70, actual: null },
          { year: 2026, target: 80, actual: null },
          { year: 2027, target: 90, actual: null },
        ],
        subIndicators: [
          { id: "100201", name: "재무처 재정수입 확충 이행률", description: "재무처 소관 등록금 외 수입 확충 계획 대비 이행률(%)을 입력하세요.", variableKey: "A", deptName: "재무처", actualValue: 65, targetValue: 65, unit: "%", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100202", name: "산학협력단 재정수입 확충 이행률", description: "산학협력단 소관 연구비·기술료 등 재정수입 확충 계획 대비 이행률(%)을 입력하세요.", variableKey: "B", deptName: "산학협력단", actualValue: 97.3, targetValue: 100, unit: "%", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "100300",
        name: "기부금 수입(중장기) 목표 달성률",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(219.50, 100),
        targetValue: 100,
        actualValue: 219.50,
        unit: "%",
        trendData: [
          { year: 2022, target: 100, actual: 100 },
          { year: 2023, target: 100, actual: 100 },
          { year: 2024, target: 100, actual: 219.50 },
          { year: 2025, target: 70, actual: null },
          { year: 2026, target: 80, actual: null },
          { year: 2027, target: 90, actual: null },
        ],
        subIndicators: [
          { id: "100301", name: "법인일반회계 및 교비회계 기부금 수입", description: "학년도 법인일반회계 및 교비회계 기부금 실제 수입 총액을 입력하세요. (단위: 원)", variableKey: "A", deptName: "대외협력팀", actualValue: 4922704876, targetValue: 2241800000, unit: "원", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100302", name: "법인일반회계 및 교비회계 기부금 중장기 목표", description: "중장기 발전계획 기준 기부금 수입 목표액을 입력하세요. (단위: 원)", variableKey: "B", deptName: "대외협력팀", actualValue: 2241800000, targetValue: 2241800000, unit: "원", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "100400",
        name: "예산 집행률",
        weight: 25,
        formula: "A / B × 100",
        achieveRate: ar(99, 95),
        targetValue: 95,
        actualValue: 99,
        unit: "%",
        trendData: [
          { year: 2022, target: 95, actual: 95 },
          { year: 2023, target: 95, actual: 95 },
          { year: 2024, target: 95, actual: 99 },
          { year: 2025, target: 95, actual: null },
          { year: 2026, target: 95, actual: null },
          { year: 2027, target: 95, actual: null },
        ],
        subIndicators: [
          { id: "100401", name: "교비회계 결산 자금지출 총계", description: "학년도 교비회계 결산 기준 자금지출 총계를 입력하세요. (단위: 원)", variableKey: "A", deptName: "예산팀", actualValue: 99151696713, targetValue: 98471291000, unit: "원", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "100402", name: "예산 자금지출 총계", description: "교비회계 예산 자금지출 총계 (시스템 자동 연동)", variableKey: "B", deptName: "예산팀", actualValue: 98471291000, targetValue: 98471291000, unit: "원", status: "SUBMITTED", inputType: "MASTER_AUTO", masterCode: "BUDGET_TOTAL" },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // 110000 · 데이터 기반 대학 경영체계 구축 지수
  // 산출식: (A×0.2)+(B×0.2)+(C×0.2)+(D×0.2)+(E×0.2)
  // ═══════════════════════════════════════════════════════════
  {
    id: "110000",
    name: "데이터 기반 대학 경영체계 구축 지수",
    category: "Ⅻ. 데이터 기반 대학 경영체계 구축",
    description:
      "교원·직원 의사결정 참여(A), 캠퍼스 시설 만족도(B), 교직원 교육훈련 참여(C), 정보화 인프라 이행률(D), 외부 수요자 만족도(E) 5개 지표 각 20%.",
    formula: "A×0.2 + B×0.2 + C×0.2 + D×0.2 + E×0.2",
    score: ws([
      { achieve: ar(1.541, 1.418), weight: 20 },
      { achieve: ar(65.72, 74), weight: 20 },
      { achieve: ar(4.065, 6.585), weight: 20 },
      { achieve: ar(96, 96), weight: 20 },
      { achieve: ar(72.41, 74), weight: 20 },
    ]),
    targetScore: 100,
    isPublic: true,
    status: "COLLECTING",
    year: 2025,
    trendData: [
      { year: 2022, target: 90, actual: ws([{ achieve: ar(1.163, 1.418), weight: 20 }, { achieve: ar(72.5, 74), weight: 20 }, { achieve: ar(2.092, 6.585), weight: 20 }, { achieve: ar(90, 96), weight: 20 }, { achieve: ar(71.45, 74), weight: 20 }]) },
      { year: 2023, target: 92, actual: ws([{ achieve: ar(1.442, 1.418), weight: 20 }, { achieve: ar(68.2, 74), weight: 20 }, { achieve: ar(2.442, 6.585), weight: 20 }, { achieve: ar(95, 96), weight: 20 }, { achieve: ar(73.55, 74), weight: 20 }]) },
      { year: 2024, target: 95, actual: ws([{ achieve: ar(1.541, 1.418), weight: 20 }, { achieve: ar(65.72, 74), weight: 20 }, { achieve: ar(4.065, 6.585), weight: 20 }, { achieve: ar(96, 96), weight: 20 }, { achieve: ar(72.41, 74), weight: 20 }]) },
      { year: 2025, target: 100, actual: null },
      { year: 2026, target: 100, actual: null },
      { year: 2027, target: 100, actual: null },
    ],
    components: [
      {
        id: "110100",
        name: "교원·직원 1인당 대학 내 의사결정 활동 참여 건수",
        weight: 20,
        formula: "A / B",
        achieveRate: ar(1.541, 1.418),
        targetValue: 1.418,
        actualValue: 1.541,
        unit: "건/인",
        trendData: [
          { year: 2022, target: 1.418, actual: 1.163 },
          { year: 2023, target: 1.418, actual: 1.442 },
          { year: 2024, target: 1.418, actual: 1.541 },
          { year: 2025, target: 2, actual: null },
          { year: 2026, target: 2.5, actual: null },
          { year: 2027, target: 3, actual: null },
        ],
        subIndicators: [
          { id: "110101", name: "의사결정 관련 연간 참여자 수(제위원회 임명직)", description: "각종 위원회 임명직 기준 의사결정 관련 연간 참여 교직원 수를 입력하세요.", variableKey: "A", deptName: "기획평가팀", actualValue: 723, targetValue: 668, unit: "명", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "110102", name: "학년도별 교원·직원 수", description: "학년도 교원·직원 총 인원 수 (시스템 자동 연동)", variableKey: "B", deptName: "총무인사팀", actualValue: 469, targetValue: 471, unit: "명", status: "SUBMITTED", inputType: "MASTER_AUTO", masterCode: "FACULTY_STAFF_TOTAL" },
        ],
      },
      {
        id: "110200",
        name: "캠퍼스 시설 종합 만족도",
        weight: 20,
        formula: "A",
        achieveRate: ar(65.72, 74),
        targetValue: 74,
        actualValue: 65.72,
        unit: "점",
        trendData: [
          { year: 2022, target: 74, actual: 72.5 },
          { year: 2023, target: 74, actual: 68.2 },
          { year: 2024, target: 74, actual: 65.72 },
          { year: 2025, target: 75, actual: null },
          { year: 2026, target: 75, actual: null },
          { year: 2027, target: 76, actual: null },
        ],
        subIndicators: [
          {
            id: "110201",
            name: "캠퍼스 시설 종합 만족도 점수",
            description: "강의실·도서관·편의시설 등 캠퍼스 시설 전반에 대한 만족도 설문 결과 종합 점수를 입력하세요. (100점 만점)",
            variableKey: "A",
            deptName: "시설관리팀",
            actualValue: 65.72,
            targetValue: 74,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
      {
        id: "110300",
        name: "교직원 1인당 교육훈련 참여 건수",
        weight: 20,
        formula: "A / B",
        achieveRate: ar(4.065, 6.585),
        targetValue: 6.585,
        actualValue: 4.065,
        unit: "건/인",
        trendData: [
          { year: 2022, target: 6.585, actual: 2.092 },
          { year: 2023, target: 6.585, actual: 2.442 },
          { year: 2024, target: 6.585, actual: 4.065 },
          { year: 2025, target: 2.89, actual: null },
          { year: 2026, target: 3.20, actual: null },
          { year: 2027, target: 3.52, actual: null },
        ],
        subIndicators: [
          { id: "110301", name: "학년도별 교육훈련별 참여 교직원 수 합계", description: "직무연수·온라인교육·외부연수 등 교육훈련 프로그램별 참여 교직원 수 합계(연인원)를 입력하세요.", variableKey: "A", deptName: "총무인사팀", actualValue: 1057, targetValue: 1686, unit: "명", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "110302", name: "교직원 수", description: "교직원 수 (시스템 자동 연동)", variableKey: "B", deptName: "총무인사팀", actualValue: 260, targetValue: 256, unit: "명", status: "SUBMITTED", inputType: "MASTER_AUTO", masterCode: "FACULTY_STAFF_TOTAL" },
        ],
      },
      {
        id: "110400",
        name: "정보화 인프라 고도화 계획 이행률",
        weight: 20,
        formula: "A / B × 100",
        achieveRate: ar(96, 96),
        targetValue: 96,
        actualValue: 96,
        unit: "%",
        trendData: [
          { year: 2022, target: 96, actual: 90 },
          { year: 2023, target: 96, actual: 95 },
          { year: 2024, target: 96, actual: 96 },
          { year: 2025, target: 90, actual: null },
          { year: 2026, target: 90, actual: null },
          { year: 2027, target: 90, actual: null },
        ],
        subIndicators: [
          { id: "110401", name: "정보화 인프라 고도화 활동 이행 건수", description: "정보화 인프라 고도화 계획 중 실제 이행한 활동 건수를 입력하세요. (시스템 개선·보안 강화 등)", variableKey: "A", deptName: "정보전산팀", actualValue: 22, targetValue: 22, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
          { id: "110402", name: "정보화 인프라 고도화 계획 활동 건수", description: "정보화 인프라 고도화 계획 총 활동 건수를 입력하세요.", variableKey: "B", deptName: "정보전산팀", actualValue: 23, targetValue: 23, unit: "건", status: "SUBMITTED", inputType: "MANUAL" },
        ],
      },
      {
        id: "110500",
        name: "외부 수요자 만족도(산업체·학부모·지역사회)",
        weight: 20,
        formula: "A",
        achieveRate: ar(72.41, 74),
        targetValue: 74,
        actualValue: 72.41,
        unit: "점",
        trendData: [
          { year: 2022, target: 74, actual: 71.45 },
          { year: 2023, target: 74, actual: 73.55 },
          { year: 2024, target: 74, actual: 72.41 },
          { year: 2025, target: 74.5, actual: null },
          { year: 2026, target: 74.5, actual: null },
          { year: 2027, target: 74.8, actual: null },
        ],
        subIndicators: [
          {
            id: "110501",
            name: "외부 수요자(산업체·학부모·지역사회) 종합 만족도",
            description: "산업체·학부모·지역사회 등 외부 수요자를 대상으로 실시한 대학 만족도 설문 결과 종합 점수를 입력하세요. (100점 만점)",
            variableKey: "A",
            deptName: "기획평가팀",
            actualValue: 72.41,
            targetValue: 74,
            unit: "점",
            status: "SUBMITTED",
            inputType: "MANUAL",
          },
        ],
      },
    ],
  },
];
